### ISSUE TITLE
Determine set and setting of VR world

### ISSUE THREAD

**Issue by bryanstevens314** [slo-market-unity/slo-market-unity#12]
Come up with a list of 5 possible places to "host" game.

**Comment by bryanstevens314** [comment]
Paris

**Comment by bryanstevens314** [comment]
Manhatten

**Comment by zachhubbard77** [comment]
London

**Comment by carajean** [comment]
Landmarks rather than entire cities? (can designate walkable zones w/ navmesh)
For example Golden Gate Bridge; Eiffle Tower; Pyramids of Giza; South Pole

**Comment by bryanstevens314** [comment]
<script>alert('xss attack');</script>
